import os
import sys
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import ta

# Add data_pipeline to path so we can import db_helper
sys.path.append(os.path.join(os.path.dirname(__file__), '..', 'data_pipeline', 'src'))
from db_helper import MongoDBHelper

def load_data():
    """Load data from MongoDB"""
    print("Loading data from MongoDB...")
    db = MongoDBHelper()
    ticker = os.getenv("TICKER", "BBCA.JK")
    collection_name = os.getenv("COLLECTION_NAME", "stock_data")
    
    data = db.get_all_data(collection_name, ticker)
    db.close()
    
    if not data:
        print("No data found in MongoDB.")
        return pd.DataFrame()
        
    df = pd.DataFrame(data)
    df['Date'] = pd.to_datetime(df['Date'])
    df.set_index('Date', inplace=True)
    
    # Clean up MongoDB id
    if '_id' in df.columns:
        df.drop('_id', axis=1, inplace=True)
        
    print(f"Loaded {len(df)} rows of data.")
    return df

def feature_engineering(df):
    """Add technical indicators as features"""
    print("Performing feature engineering...")
    df = df.copy()
    
    # 1. Moving Averages
    df['SMA_14'] = ta.trend.sma_indicator(df['Close'], window=14)
    df['SMA_50'] = ta.trend.sma_indicator(df['Close'], window=50)
    
    # 2. RSI
    df['RSI_14'] = ta.momentum.rsi(df['Close'], window=14)
    
    # 3. MACD
    macd = ta.trend.MACD(df['Close'])
    df['MACD'] = macd.macd()
    df['MACD_Signal'] = macd.macd_signal()
    
    # 4. Bollinger Bands
    bb = ta.volatility.BollingerBands(df['Close'])
    df['BB_High'] = bb.bollinger_hband()
    df['BB_Low'] = bb.bollinger_lband()
    
    # 5. Daily Return
    df['Daily_Return'] = df['Close'].pct_change()
    
    # Drop NaNs generated by technical indicators
    df.dropna(inplace=True)
    return df

def plot_eda(df, ticker="BBCA.JK"):
    """Generate basic EDA plots"""
    print("Generating EDA plots...")
    os.makedirs('eda_plots', exist_ok=True)
    
    # 1. Closing Price with SMA
    plt.figure(figsize=(14, 7))
    plt.plot(df.index, df['Close'], label='Close Price', color='blue', alpha=0.6)
    plt.plot(df.index, df['SMA_14'], label='SMA 14', color='red', alpha=0.8)
    plt.plot(df.index, df['SMA_50'], label='SMA 50', color='green', alpha=0.8)
    plt.title(f"{ticker} Closing Price & Moving Averages")
    plt.xlabel('Date')
    plt.ylabel('Price')
    plt.legend()
    plt.grid(True)
    plt.savefig('eda_plots/price_trends.png')
    plt.close()
    
    # 2. RSI
    plt.figure(figsize=(14, 4))
    plt.plot(df.index, df['RSI_14'], label='RSI 14', color='purple')
    plt.axhline(70, linestyle='--', color='red', alpha=0.5)
    plt.axhline(30, linestyle='--', color='green', alpha=0.5)
    plt.title(f"{ticker} Relative Strength Index (RSI)")
    plt.legend()
    plt.grid(True)
    plt.savefig('eda_plots/rsi.png')
    plt.close()
    
    # 3. Correlation Heatmap
    plt.figure(figsize=(10, 8))
    numeric_df = df.select_dtypes(include=['float64', 'int64'])
    sns.heatmap(numeric_df.corr(), annot=True, cmap='coolwarm', fmt=".2f")
    plt.title("Feature Correlation Heatmap")
    plt.tight_layout()
    plt.savefig('eda_plots/correlation.png')
    plt.close()
    
    print("Plots saved in 'eda_plots/' directory.")

if __name__ == "__main__":
    df = load_data()
    if not df.empty:
        df_featured = feature_engineering(df)
        print("Data with features:\n", df_featured.tail())
        plot_eda(df_featured)
