apiVersion: v1
kind: Service
metadata:
  name: finance-api-service
spec:
  type: NodePort # Use NodePort or LoadBalancer for external access depending on K8s setup
  selector:
    app: finance-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30080
